author:
  name: Joaquin Borrego Fernandez
  email: juakylc14@gmail.com
  
spring:
  application:
    name: watchlist

    #DB Config
  datasource:
    url: ${db:jdbc:postgresql://localhost:5432/watchlist&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory}
    username: ${user:root}
    password: ${pass:root}

  jpa:
    hibernate:
      ddl-auto: none

    defer-datasource-initialization:  true
  sql:
    init:
      data-locations:
      - classpath:db/postgresql/schema.sql
      - classpath:db/postgresql/data.sql
      #La siguiente propiedad indica cuando crear la base de datos. Si está en always la crea siempre, si está en never nunca.
      mode: ${dbinitmode:never}
#Swagger config
springdoc:
  swagger-ui: 
    path: /doc

#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.show-sql = false
